"""create doc type table

Revision ID: 4e868ead5a56
Revises: 1a31ce608336
Create Date: 2024-10-21 19:20:52.589046

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e868ead5a56'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CHARGING_STATION_INSTALL_REPORT', name='document_type_enum'), nullable=False),
    sa.Column('file_extension', sa.Enum('CSV', name='file_extension'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_type')
    # ### end Alembic commands ###
